-- Supabase PostgreSQL Schema for Campaigns
-- Matching the 5-state campaign lifecycle: PENDING, RUNNING, COMPLETED, FAILED, CANCELLED

CREATE TABLE IF NOT EXISTS campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spreadsheet_title VARCHAR(255),
    spreadsheet_url TEXT,
    recipient_column VARCHAR(100) DEFAULT 'email',
    subject TEXT NOT NULL,
    body_template TEXT NOT NULL,
    scheduled_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status VARCHAR(50) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    sender_email VARCHAR(255),
    chrome_profile VARCHAR(255),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for scheduler poll query: WHERE status = 'PENDING' AND scheduled_at <= NOW() ORDER BY scheduled_at ASC
CREATE INDEX IF NOT EXISTS idx_campaigns_status_scheduled ON campaigns(status, scheduled_at);
